.github/workflows/assemble.yml

Write permissions are needed in order to assume the aws role. See the docs https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-permissions-settings

Add id-token write permissions to GHA

---

README.md
package.json
sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml

We weren't at all well communicating the state of this repository at the current time, which was leading to confusion and mismatched expectations from team members.
I'm hoping the change presented in this pull request, as well as the creation of the milestone referenced within, will help make this clearer for all.

Clarify versioning state

---

sdk-manifests/ably-java.yaml
sdk.yaml

1.2.0 Feature: Push Notifications: Local Device State

---

manifest.js
manifest.test.js

I'm quite surprised that I hadn't spotted this oversight until now. 😳 
An object was being returned incorrectly for nodes that didn't exist in the manifest.
I've also added some testing. 🤞 
Discovered while working on the family of pull requests addressing #3.

Fix `Manifest`'s `find` method

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

It doesn't make sense to be able to disable automatic connection but then not have access to `connect` or `close` methods on the Realtime instance or its connection instance.
Therefore, I've expanded this feature to include more specification points and have renamed it accordingly.

1.2.0 Feature: Rename and expand the feature linked to `autoConnect` client options

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

There was no benefit in having a discrete feature node for the connection recovery string client option.
It's implicitly required for this functionality to work at all, and there's potential that client libraries could decide to offer a more idiomatic API that means it's not even framed via any client options API.

1.2.0 Feature: Realtime: Connection Recovery

---

sdk.yaml

One of a family of pull requests addressing https://github.com/ably/features/issues/3.
I could see no evidence that either the Java / Android or Ruby SDKs had methods to allow you to set options for REST channel instances.

1.2.0 Feature: REST: Channel Encryption (set channel options)

---

package-lock.json
package.json

We were only using it for YAML, in fact.
Enough is enough. Fighting this tool has taken up too much time. We shall find a replacement.
see: https://github.com/ably/features/pull/35

Remove `prettier` tool

---

sdk-manifests/ably-java.yaml
sdk.yaml

I could see no evidence that the Ruby SDK supports this.

1.2.0 Feature: Realtime: Channel Modes

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

Continues the naming style established in #21 for contexts where state has a synchronous getter as well as an asynchronous event path (e.g. `EventEmitter`).

1.2.0 Feature: Realtime: Channel State

---

.github/workflows/check.yml

I should have done this under https://github.com/ably/features/pull/36

Remove now-superfluous step leftover from `prettier` debugging

---

build.js

This is a small thing that had been niggling me for a while. I was initially just dumping the 'docs' links above the synopsis, however that had the result of making cells taller than they really needed to be. I've now tucked them away to the right hand side of the cell.
So, where we did have this:
We now have this:

Improve layout when both Synopsis and Docs links are available for a feature node

---

build.js

For the moment that means either 'docs' or 'faq', but in a subsequent PR my plan is to start linking to a few Ably blog articles also - so will be adding 'blog' then, too.

Make documentation buttons friendlier

---

README.md

Small refinement to guidance which I noticed was out of sync with reality.

Remove feature node naming restriction which we were already contravening legitimately

---

build.js
sdk-manifests/ably-java.yaml
sdk-manifests/ably-php.yaml
sdk-node-properties.js
sdk.yaml

Partially addresses @lmars' observation around the potential oversight of `ErrorInfo`, specifically the "etc.." including request identifiers for failed requests.

Refine `REST: Request Identifiers` regarding returned `ErrorInfo` API

---

build.js
sdk-manifests/ably-java.yaml
sdk-manifests/ably-php.yaml
sdk-manifests/ably-ruby.yaml
sdk-node-properties.js
sdk.yaml

Builds upon the work done in #61 to fully address @lmars' observations around the potential oversight of `ErrorInfo`.

Add feature nodes for `ErrorInfo`

---

build.js
sdk-node-properties.js
sdk.yaml
transform.js
transform.test.js

Completes the work I believe is required to address @lmars' observations around the potential oversight of Fallbacks, building on the work done in #66.
I had to enhance the `requires` feature node property to allow a feature node to require multiple feature nodes.

Add feature node for `RTN17e` - REST following Realtime fallback host selection

---

.markdownlint-cli2.yaml
README.md
build.js
sdk-node-properties.js
sdk.yaml
transform.js
transform.test.js

I've added some explanatory text around the use of the `requires` feature node property.
I've also added `REST` as a requirement to a few nodes that sit outside of the `REST` feature tree.
This thinking, plus prototyping, will help when working on https://github.com/ably/features/issues/64.

Expand on `requires` - Feature Node Dependencies

---

README.md
sdk-manifests/ably-java.yaml
sdk-manifests/ably-php.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

Addresses an observation made by @owenpearson when we had an informal knowledge sharing call discussing the work taking place in this repository.
It seemed logical to me to have a 'Push Notifications' root node when I created it, however there is a clear split between 'Realtime' and 'REST' subordinate features, so I delete that root node in this pull request and move its children to locations appropriate to their operational scope.
See: [05/10/22 SDK Biweekly Sync - Canonical Features](https://ably.atlassian.net/wiki/spaces/SDK/pages/2338226184/05+10+22+SDK+Biweekly+Sync+-+Canonical+Features) (internal)

Refactor Push Notifications

---

README.md
sdk-manifests/ably-ruby.yaml
sdk-node-properties.js
sdk.yaml

Now that the features spec [has moved](https://github.com/ably/specification/issues/1) from [the `ably/docs` repository](https://github.com/ably/docs) to its new home in [the `ably/specification` repository](https://github.com/ably/specification), it's also published to a different location.

Redirect feature spec point references from `docs.ably.com` to `sdk.ably.com`

---

sdk.yaml

Addresses @lmars' observation around the potential oversight of "Publish message with name", as well as "Publish multiple messages".
Having discussed this with @owenpearson, @Peter-Maguire and @stmoreau earlier today - we agreed that it would be incomplete for an SDK to implement publish for either REST or Realtime without offering all of the overloads we advertise under [RSL1a](https://sdk.ably.com/builds/ably/specification/main/features/#RSL1a).
I queried the purpose of [RSL1l](https://sdk.ably.com/builds/ably/specification/main/features/#RSL1l) (see [this internal Slack thread](https://ably-real-time.slack.com/archives/C030C5YLY/p1665494612333419)) which has resulted in https://github.com/ably/features/pull/73, that …

Expand `Channel: Publish` feature nodes for `REST` and `Realtime`

---

build.js
sdk.yaml

An oversight I spotted when exploring `RSL1`, in response to https://github.com/ably/features/issues/3#issuecomment-1260538592.
As I understand, from [this Slack thread (internal)](https://ably-real-time.slack.com/archives/C030C5YLY/p1665494612333419), this feature is probably only offered by [our `ably-js` SDK](https://github.com/ably/ably-js) and _might_ be offered by [our `ably-ruby` SDK](https://github.com/ably/ably-ruby) but in a different way.
We can add compliance to manifests at a later date. For now, I was just keen to get this feature surfaced and explained.

Add `Parameters for Query String` (`RSL1l`) to `REST: Channel: Publish` feature

---

sdk-manifests/ably-php.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

Addresses @lmars' observation around the potential oversight of "Channel status".
Of these two features:
- `Channel Details`: has been specified and implemented in some SDKs (those that tend to be used server-side)
- `Enumerate`: has not yet been specified, nor implemented in any SDKs

Add feature nodes for Channel Status REST APIs

---

sdk.yaml

Addresses @lmars' observation around the potential oversight of "Incremental backoff".
At the time of writing this opening comment none of the SDKs for which we have manifests in this repository at the moment have implemented this feature, however it is:
- done for JS: https://github.com/ably/ably-js/pull/1008
- WIP for .NET: https://github.com/ably/ably-dotnet/pull/1176

Add feature node for `Incremental Backoff` to `Realtime: Connection` (`RTB1`)

---

sdk.yaml

Finishes addressing the potential oversight of `Message` extras.
I started adding these references in https://github.com/ably/features/pull/72, but deferred adding them to other feature nodes that weren't within scope of the change being made in that pull request until this pull request.

Add more references to `Message` type spec points (`TM1`, `TM2` and `TM4`)

---

main.css
sdk.yaml

Addresses @lmars observation around the potential oversight of "Subscribe to messages by name", aligning with the synopsis changes made in #72.
Also, some other related embellishments.

Enhance `Attach` and `Subscribe` feature nodes within `Realtime: Channel`

---

build.js
package-lock.json
package.json
tailwind.config.js

Addressing issue https://github.com/ably/features/issues/87
I have added some styling that fixes the table widths issue which gives us the following rendering:
In order to do so I had to create a mini Tailwind plugin to support the `writing-mode` CSS property which is not supported out of the box by Tailwind (see https://github.com/tailwindlabs/tailwindcss/discussions/2494). Note: [it is supported by major browsers](https://caniuse.com/?search=writing-mode).
That has resulted in a need to move the `tailwindcss` dependency from `devDependencies` to `dependencies` in the `package.json` to keep the linter happy.

Add styling to make the table cells have consistently the same width

---

CONTRIBUTING.md
README.md

Now that our conformed release process has been well documented elsewhere, there's not much additional detail that needs to live in the guidance here.
Closes #5. Closes #12.

Document Release Process and Usage

---

build.js

This reduces the width of the columns for each SDK, allowing the viewer to comfortably inspect it in a narrower browser window. Especially helpful now that we've got many more SDK manifests created, creating more SDK columns.
Takes us from this:
to this:

Reduce the size of the icons in the rendered matrix

---

sdk-manifests/ably-dotnet.yaml
sdk.yaml

- Depends on https://github.com/ably/ably-dotnet/pull/1195
- Added agents and runtime under Agent Identifier
- Removed deprecated `uwp` runtime comment as per https://github.com/ably/ably-dotnet/pull/1101

Added missing agents feature to dotnet

---

build.js
sdk-node-properties.js
sdk.yaml

This is an idea I came up with when trying to think of ways to make the rendered features matrix easier to visually track when scrolling vertically.
The change presented in this pull request marks a number of the nodes in the canonical feature list tree as "markers", representing the idea that they do not carry direct user-facing value, existing to provide branch points for groups of related features.
Those marker nodes are then formatted differently (row background colour, bold font for the node name, no ticks or crosses per SDK).
Before this change:
After this change:

Marker nodes

---

build.js
manifest.js
manifest.test.js
sdk-manifests/ably-ruby.yaml

Fixes a manifest validation oversight introduced in #106 and spotted by @stmoreau when we verbally discussing that change. The Ruby manifest was indicating compliance with `Realtime: Authentication` without further indicating compliance with any of its child nodes. The `Realtime: Authentication` node is now a feature heading, so can only bring value to a manifest if at least one of its children is also included.

Disallow compliance with Heading feature node only

---

core/compare.js
core/manifest.js
core/matrix.js
render/build.js
render/html.js

The HTML rendering was very much inter-mingled with the core business logic of matrix generation (canonical features list exploration and compliance checks against SDK manifests).
This pull request addresses that and should make this area of the codebase easier to unit test.
I considered adding some tests for this new `MatrixGenerator` class (essentially, checking the code paths within the file-internal `generateMatrix` function), however I decided that the complexity/time involved to make those outweighed the benefit to the codebase as these parts were already well proven in the original location.

Extract matrix generation
