ably/features

README.md

Document the filename and location agreed upon for SDK manifest files

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: REST: Request

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: REST: Statistics (stats) Query

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: REST: Time

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

I've not been able to easily or quickly confirm whether this feature is definitely implemented in Java or Ruby SDKs, so am going to create issues to look into that later.

1.2.0 Feature: Realtime: Auth, Get confirmed client identifier

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: Realtime: Connection State

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: Realtime: Ping

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: Realtime: Get Connection Identifier

---

.github/workflows/check.yml
package-lock.json
package.json

Assisting me in debugging CI-only checks failure in #24, which will target the branch underlying this pull request soon.

Upgrade `prettier` and add debug on failure

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: REST: Publish

---

sdk-manifests/ably-java.yaml
sdk.yaml

One of a family of pull requests addressing https://github.com/ably/features/issues/3.

1.2.0 Feature: Realtime: Publish (fix up)

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: Realtime: Channel Encryption (set channel options)

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: Realtime: Channel Rewind (set channel options)

---

sdk.yaml

1.2.0 Feature: Realtime: Deltas Subscription (enhancements)

---

sdk.yaml

1.2.0 Feature: Realtime: Presence (fix up)

---

sdk-manifests/ably-java.yaml
sdk-manifests/ably-ruby.yaml
sdk.yaml

1.2.0 Feature: Realtime: Channel Message History

---

README.md
sdk-manifests/ably-java.yaml
sdk.yaml

1.2.0 Feature: REST: Channel Push Notifications

---

README.md
sdk.yaml

Remove references to asynchronous and synchronous from synopsis

---

README.md
sdk.yaml

Remove implicit wording

---

sdk.yaml

One of a family of pull requests addressing https://github.com/ably/features/issues/3.

Synopsis Enhancements: Realtime Channel Attach and Subscribe

---

build.js
sdk.yaml

Building on the work done in #51 to add links to blog posts.

Add blog post links

---

sdk-manifests/ably-ruby.yaml
sdk.yaml

One of a family of pull requests addressing https://github.com/ably/features/issues/3.

1.2.0 Feature: HTTP/2

---

README.md
sdk.yaml

Addresses @lmars' observation around the potential oversight of Pagination in the canonical features list.

Clarify Pagination, as well as 'What makes a Feature?'

---

build.js
sdk-manifests/ably-cocoa.yaml

Closes https://github.com/ably/ably-cocoa/issues/1443

Cocoa sdk manifest

---

CONTRIBUTING.md
build.js
nodemon.json
package-lock.json
package.json

Closing issue https://github.com/ably/features/issues/84
Added some dev dependencies that will allow serving the website during local development and will enable hot reloading for maximum efficiency 🚀
Preview of the intended behavior can be seen in [this link](https://user-images.githubusercontent.com/15115885/196560441-72875fbf-f225-4835-b178-cc76cb066d03.mov).

Add HTTP server for local development preview

---

build.js
sdk-manifests/ably-dotnet.yaml

- Fixed https://github.com/ably/ably-dotnet/issues/1175

Add dotnet SDK manifest

---

build.js
sdk-manifests/ably-flutter.yaml

Resolves https://github.com/ably/ably-flutter/issues/432.

Add manifest for our Flutter plugin

---

sdk-manifests/ably-flutter.yaml
sdk-manifests/ably-java.yaml

fix: disconnectedRetryTimeout not implemented in ably-java

---

core/html-matrix-build.js
core/package-lock.json
core/package.json
render/build.js
render/package-lock.json
render/package.json

Final piece in the jigsaw (I think 🤞) before I can now work on creating a GitHub action (new repository) which will utilise this core functionality.

Extract build

---

.github/workflows/assemble.yml
.github/workflows/check.yml
.github/workflows/publish-core.yml

I'm going to need to land this to the `main` branch for GitHub to pick up the workflow and allow me to run it manually.
I also took this as an opportunity to improve existing workflows as they were using older versions of the third-party actions upon which they depended.

Release process

---

sdk.yaml

add 'OS Connectivity Events' feature

---

render/package-lock.json
render/package.json

- adds "OS Connectivity events"

Release 1.2.1
